# main.py
import os
import time
import shutil

# Colored banner
BANNER = """
\033[1;34m╔══════════════════════════════════════════════════╗\033[0m
\033[1;36m║   CHIKATILO MATRP AND RUAN — Forum tracker bot    ║\033[0m
\033[1;34m╚══════════════════════════════════════════════════╝\033[0m
"""

CONFIG_TEMPLATE = '''# config.py - autogenerated, DO NOT COMMIT SECRETS TO PUBLIC REPO
VK_TOKEN = "{vk_token}"
XF_USER = "{xf_user}"
XF_SESSION = "{xf_session}"
XF_TFA_TRUST = "{xf_tfa_trust}"
FORUM_BASE = "https://forum.matrp.ru"
POLL_INTERVAL_SEC = {poll_interval}
'''

def setup_config(path="config.py"):
    if os.path.exists(path):
        print(BANNER)
        print("config.py already exists — using existing configuration.")
        return
    print(BANNER)
    print("Первичная настройка бота — введи свои токены/куки.")
    vk = input("VK_TOKEN: ").strip()
    xf_user = input("XF_USER: ").strip()
    xf_session = input("XF_SESSION: ").strip()
    xf_tfa = input("XF_TFA_TRUST: ").strip()
    poll = input("POLL_INTERVAL_SEC (default 20): ").strip() or "20"
    content = CONFIG_TEMPLATE.format(
        vk_token=vk.replace('"','\\"'),
        xf_user=xf_user.replace('"','\\"'),
        xf_session=xf_session.replace('"','\\"'),
        xf_tfa_trust=xf_tfa.replace('"','\\"'),
        poll_interval=poll
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Сохранено в config.py — запускаю бота...")

def main():
    setup_config("config.py")
    # Lazy imports
    from bot.vk_bot import VKBot
    from bot.forum_tracker import ForumTracker
    print(BANNER)
    vk = VKBot()
    tracker = ForumTracker(vk)
    # start services
    vk.start()
    tracker.start()
    print("\nБот запущен. Для остановки Ctrl+C\n")
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        print("Выход...")

if __name__ == "__main__":
    main()
