# main.py
import os
import sys
import time
import signal
from pathlib import Path

BANNER = r"""
╔════════════════════════════════════════════════════════════════════╗
║                                                                    ║
║   ██████╗██╗  ██╗██╗██╗  ██╗  CHIKATILO MATRP AND RUAN  BOT        ║
║                                                                    ║
╚════════════════════════════════════════════════════════════════════╝
"""

CONFIG_TEMPLATE = '''# config.py - autogenerated. Do NOT commit secrets to public repo.
VK_TOKEN = "{vk_token}"

# Forum cookies (XF)
XF_USER = "{xf_user}"
XF_SESSION = "{xf_session}"
XF_TFA_TRUST = "{xf_tfa_trust}"

FORUM_BASE = "https://forum.matrp.ru"
POLL_INTERVAL_SEC = {poll_interval}

# Optional: comma-separated admin user IDs (e.g. "12345,67890")
ADMINS = "{admins}"
'''

def interactive_setup(path="config.py"):
    if os.path.exists(path):
        print("config.py already present, skipping interactive setup.")
        return
    print(BANNER)
    print("Первичная настройка бота — введите значения (пусто = оставит пустые строки).")
    vk_token = input("VK_TOKEN: ").strip()
    xf_user = input("XF_USER (cookie): ").strip()
    xf_session = input("XF_SESSION (cookie): ").strip()
    xf_tfa = input("XF_TFA_TRUST (cookie): ").strip()
    poll = input("POLL_INTERVAL_SEC (default 20): ").strip() or "20"
    admins = input("ADMINS (comma-separated user IDs, optional): ").strip()
    content = CONFIG_TEMPLATE.format(
        vk_token=vk_token.replace('"','\\"'),
        xf_user=xf_user.replace('"','\\"'),
        xf_session=xf_session.replace('"','\\"'),
        xf_tfa_trust=xf_tfa.replace('"','\\"'),
        poll_interval=poll,
        admins=admins.replace('"','\\"')
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("config.py created. Starting bot...")

def main():
    interactive_setup("config.py")

    # adjust path to include bot package
    sys.path.insert(0, os.path.abspath("."))

    from bot.vk_bot import VKBot
    from bot.forum_tracker import ForumTracker

    vk = VKBot()
    tracker = ForumTracker(vk)

    # graceful stop on signals
    def shutdown(signum, frame):
        print("Signal received, stopping...")
        try:
            tracker.stop()
        except Exception:
            pass
        try:
            vk.stop()
        except Exception:
            pass
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    print(BANNER)
    print("Запуск сервисов...")

    vk.start()         # starts longpoll thread
    tracker.start()    # starts tracker thread

    print("Сервисы запущены. Бот работает.")
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        shutdown(None, None)

if __name__ == "__main__":
    main()
