# main.py
import os
import time
import textwrap

BANNER = r"""
██╗   ██╗██╗  ██╗██╗███╗   ██╗
██║   ██║██║ ██╔╝██║████╗  ██║
██║   ██║█████╔╝ ██║██╔██╗ ██║
╚██╗ ██╔╝██╔═██╗ ██║██║╚██╗██║
 ╚████╔╝ ██║  ██╗██║██║ ╚████║
  ╚═══╝  ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
      VK FORUM TRACKER BOT
"""

CONFIG_TEMPLATE = '''# config.py - autogenerated, DO NOT COMMIT SECRETS TO PUBLIC REPO
# Put your VK community token and forum cookies here.
VK_TOKEN = "{vk_token}"

# Forum cookies (XenForo)
XF_USER = "{xf_user}"
XF_SESSION = "{xf_session}"
XF_TFA_TRUST = "{xf_tfa_trust}"

# Forum base (do not change)
FORUM_BASE = "https://forum.matrp.ru"

# Polling interval in seconds
POLL_INTERVAL_SEC = {poll_interval}
'''

def prompt_config(path="config.py"):
    if os.path.exists(path):
        print("config.py already exists — will not overwrite.")
        return

    print(BANNER)
    print("Setup config (values will be written to config.py).")
    vk = input("Enter VK group token (VK_TOKEN): ").strip()
    print("Now enter forum cookies (xf_user, xf_session, xf_tfa_trust).")
    xf_user = input("XF_USER: ").strip()
    xf_session = input("XF_SESSION: ").strip()
    xf_tfa = input("XF_TFA_TRUST: ").strip()
    poll = input("POLL_INTERVAL_SEC (default 20): ").strip() or "20"

    content = CONFIG_TEMPLATE.format(
        vk_token=vk.replace('"','\\"'),
        xf_user=xf_user.replace('"','\\"'),
        xf_session=xf_session.replace('"','\\"'),
        xf_tfa_trust=xf_tfa.replace('"','\\"'),
        poll_interval=poll
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    print("Saved config.py — starting bot...")

def main():
    prompt_config("config.py")

    # Lazy imports to allow config to be created first
    from bot.vk_bot import VKBot
    from bot.forum_tracker import ForumTracker

    vk = VKBot()
    tracker = ForumTracker(vk)

    # start VK longpoll in background (non-blocking)
    vk.start()

    # start forum tracker loop (non-blocking)
    tracker.start()

    print("\nBot is running. Press Ctrl+C to stop.")
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        print("Shutting down...")

if __name__ == "__main__":
    main()
